name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r real_estate_analyzer/requirements.txt
          pip install -r tests/requirements-test.txt

      - name: Run unit tests
        run: |
          python -m pytest tests/ -v --tb=short -m "not slow and not integration"

      - name: Run integration tests
        run: |
          python -m pytest tests/ -v --tb=short -m "integration and not slow"

      - name: Run all tests with coverage
        run: |
          python -m pytest tests/ --cov=real_estate_analyzer --cov-report=xml --cov-report=term-missing

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
